// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.

/**
\mainpage UFS Tools

\anchor mainpage-top

\section gridspec Generating Grid Projection Files

\section esmf Computing ESMF Remapping Coefficients

\section remapper Remapping Analysis Variable Fields

*/
